### ISSUE TITLE
Got error when running script

### ISSUE THREAD

**Issue by uilcxr** [cernceph/ceph-scripts#8]
Hi there,

I'm newbie to ceph and python. Got some error when I try the script.
Kindly advice how to fix that. Thanks in advance.

Traceback (most recent call last):
  File "./ceph-gentle-reweight.py", line 190, in <module>
    main(sys.argv[1:])
  File "./ceph-gentle-reweight.py", line 185, in main
    reweight_osds(drain_osds, max_pgs_backfilling, max_latency, delta_weight, target_weight, test_pool, start_time, end_time, allowed_days, interval, really)
  File "./ceph-gentle-reweight.py", line 90, in reweight_osds
    latency = measure_latency(test_pool)
  File "./ceph-gentle-reweight.py", line 46, in measure_latency
    latency_ms = 1000*float(latency)
ValueError: could not convert string to float:

Thanks,
Allen

**Comment by dvanders** [comment]
That script requires a 'test' pool -- check the source code to see what its doing.
